const Icon = {
  "晴": "icon-qing",
  "多云": "icon-duoyun",
  "阴": "icon-yin",
  "阵雨": "icon-zhenyu",
  "雷阵雨": "icon-leizhenyu",
  "雷阵雨伴有冰雹": "icon-leizhenyubanyoubingbao",
  "雨夹雪": "icon-yujiaxue",
  "小雨": "icon-xiaoyu",
  "中雨": "icon-zhongyu",
  "大雨": "icon-dayu",
  "暴雨": "icon-baoyu",
  "大暴雨": "icon-dabaoyu",
  "特大暴雨": "icon-tedabaoyu",
  "阵雪": "icon-zhenxue",
  "小雪": "icon-xiaoxue",
  "中雪": "icon-zhongxue",
  "大雪": "icon-daxue",
  "暴雪": "icon-baoxue",
  "雾": "icon-wu",
  "冻雨": "icon-dongyu",
  "沙尘暴": "icon-dongyu",
  "小到中雨": "icon-xiaoyu-zhongyu",
  "中到大雨": "icon-zhongyu-dayu",
  "大到暴雨": "icon-dayu-baoyu",
  "暴雨到大暴雨": "icon-baoyu-dabaoyu",
  "大暴雨到特大暴雨": "icon-dabaoyu-tedabaoyu",
  "小到中雪": "icon-xiaoxue-zhongxue",
  "中到大雪": "icon-zhongxue-daxue",
  "大到暴雪": "icon-daxue-baoxue",
  "浮尘": "icon-fuchen",
  "扬沙": "icon-yangsha",
  "强沙尘暴": "icon-qiangshachenbao",
  "霾": "icon-wumai"
}
export default Icon;